spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${CI_DB_HOST:localhost}:${CI_DB_PORT:3306}/${CI_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&sessionVariables=time_zone='%2B09:00'&characterEncoding=UTF-8
    username: ${CI_DB_USER}
    password: ${CI_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: baseline

  security:
    oauth2:
      google:
        client-ids: security-ouath2-google-client-id

auth:
  refresh:
    expiration-days: 365

jwt:
  secret: jwt-secret-fot-test-jwt-secret-for-test
  access-token:
    expiration-minutes: 365

ai:
  websocket:
    url: ws://localhost:0
    timeout: 30000
  server:
    base-url: http://localhost
